helmReleaseName: context-mesh
namespace: team-latency-labs
helmChart: ./helm/nurix-service

dockerfilePath: ./helm/nextjs-service.Dockerfile
docker:
  buildArgs:
    PORT: "3000"

ingress:
  enabled: true
  scheme: "internet-facing"
  listenPorts: '[{"HTTP": 80},{"HTTPS": 443}]'
  hosts:
    - host: "context-mesh.hack.nurixlabs.tech"
      paths:
        - path: /
          pathType: Prefix

service:
  targetPort: 3000

application:
  container:
    port: 3000
    targetPort: 3000
  healthCheck:
    liveness:
      enabled: true
      path: /
      port: 3000
      initialDelaySeconds: 90
      periodSeconds: 15
      timeoutSeconds: 10
      failureThreshold: 5
    readiness:
      enabled: true
      path: /
      port: 3000
      initialDelaySeconds: 90
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

replicaCount: 1

vpnIngress:
  enabled: false

wssIngress:
  enabled: false

internalIngress:
  enabled: false

serviceMonitor:
  enabled: false

podMonitor:
  enabled: false

configMap:
  enabled: false

secret:
  enabled: false

serviceAccount:
  create: true
