helmReleaseName: context-mesh
namespace: team-latency-labs
helmChart: ./helm/nurix-service

dockerfilePath: ./helm/nextjs-service.Dockerfile
docker:
  buildArgs:
    PORT: "3000"

ingress:
  enabled: true
  host: context-mesh.hack-apr-26.nurixlabs.com
  path: /
  pathType: Prefix

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

replicaCount: 1
