import { VerticalConfig } from "@/types/vertical";

export const healthcareVertical: VerticalConfig = {
  id: "healthcare",
  name: "Healthcare",
  description: "Hospital operations, patient journeys, and clinical intelligence",

  nodeTypes: [
    {
      label: "Profile",
      displayName: "name",
      icon: "🏥",
      properties: [
        { name: "profile_id", type: "string", unique: true },
        { name: "name", type: "string" },
        { name: "age", type: "integer" },
        { name: "gender", type: "string", enum: ["Male", "Female", "Other"] },
        { name: "blood_group", type: "string" },
        { name: "city", type: "string" },
        { name: "insurance_provider", type: "string" },
      ],
    },
    {
      label: "Visit",
      displayName: "type",
      icon: "📋",
      properties: [
        { name: "visit_id", type: "string", unique: true },
        { name: "type", type: "string", enum: ["Emergency", "Outpatient", "Inpatient", "Follow-up", "Surgery"] },
        { name: "timestamp", type: "datetime" },
        { name: "department", type: "string" },
        { name: "status", type: "string", enum: ["Active", "Discharged", "Transferred", "Deceased"] },
        { name: "priority", type: "string", enum: ["Critical", "High", "Medium", "Low"] },
        { name: "duration_hours", type: "float" },
        { name: "confidence_score", type: "float" },
      ],
    },
    {
      label: "Diagnosis",
      displayName: "name",
      icon: "🔬",
      properties: [
        { name: "diagnosis_id", type: "string", unique: true },
        { name: "icd_code", type: "string" },
        { name: "name", type: "string" },
        { name: "severity", type: "string", enum: ["Critical", "Severe", "Moderate", "Mild"] },
        { name: "chronic", type: "boolean" },
      ],
    },
    {
      label: "Treatment",
      displayName: "name",
      icon: "💊",
      properties: [
        { name: "treatment_id", type: "string", unique: true },
        { name: "name", type: "string" },
        { name: "type", type: "string", enum: ["Procedure", "Surgery", "Therapy", "Observation"] },
        { name: "cost", type: "float" },
        { name: "duration_hours", type: "float" },
        { name: "success", type: "boolean" },
      ],
    },
    {
      label: "Medication",
      displayName: "name",
      icon: "💉",
      properties: [
        { name: "medication_id", type: "string", unique: true },
        { name: "name", type: "string" },
        { name: "dosage", type: "string" },
        { name: "frequency", type: "string" },
        { name: "duration_days", type: "integer" },
      ],
    },
    {
      label: "Provider",
      displayName: "name",
      icon: "👨‍⚕️",
      properties: [
        { name: "provider_id", type: "string", unique: true },
        { name: "name", type: "string" },
        { name: "specialization", type: "string" },
        { name: "department", type: "string" },
        { name: "experience_years", type: "integer" },
      ],
    },
    {
      label: "InsuranceClaim",
      displayName: "status",
      icon: "📄",
      properties: [
        { name: "claim_id", type: "string", unique: true },
        { name: "amount", type: "float" },
        { name: "status", type: "string", enum: ["Approved", "Denied", "Pending", "Partial"] },
        { name: "denial_reason", type: "string" },
        { name: "payer", type: "string" },
      ],
    },
    {
      label: "Protocol",
      displayName: "name",
      icon: "📑",
      properties: [
        { name: "protocol_id", type: "string", unique: true },
        { name: "name", type: "string" },
        { name: "version", type: "string" },
        { name: "condition", type: "string" },
        { name: "standard_treatment", type: "string" },
        { name: "status", type: "string", enum: ["active", "superseded", "revoked"] },
      ],
    },
    {
      label: "Outcome",
      displayName: "type",
      icon: "📊",
      properties: [
        { name: "outcome_id", type: "string", unique: true },
        { name: "type", type: "string", enum: ["Recovered", "Improved", "Unchanged", "Deteriorated", "Deceased"] },
        { name: "readmission", type: "boolean" },
        { name: "days_to_readmission", type: "integer" },
        { name: "follow_up_scheduled", type: "boolean" },
      ],
    },
    {
      label: "Department",
      displayName: "name",
      icon: "🏢",
      properties: [
        { name: "department_id", type: "string", unique: true },
        { name: "name", type: "string" },
        { name: "type", type: "string", enum: ["Clinical", "Surgical", "Emergency", "Diagnostic", "Support"] },
        { name: "capacity", type: "integer" },
      ],
    },
    {
      label: "Commitment",
      displayName: "promise_text",
      icon: "🤝",
      properties: [
        { name: "commitment_id", type: "string", unique: true },
        { name: "promise_text", type: "string" },
        { name: "deadline", type: "datetime" },
        { name: "status", type: "string", enum: ["open", "fulfilled", "breached", "cancelled"] },
        { name: "assignee", type: "string" },
      ],
    },
  ],

  colors: {
    Profile: "#10b981",
    Identity: "#6b7280",
    Visit: "#3b82f6",
    Diagnosis: "#ef4444",
    Treatment: "#8b5cf6",
    Medication: "#06b6d4",
    Provider: "#14b8a6",
    InsuranceClaim: "#f97316",
    Protocol: "#eab308",
    Outcome: "#ec4899",
    Department: "#6366f1",
    Commitment: "#84cc16",
  },

  filters: [
    { id: "department", label: "Department", type: "select", options: ["Cardiology", "Orthopedics", "General Medicine", "Emergency", "Neurology", "Pulmonology"], cypherField: "v.department" },
    { id: "priority", label: "Priority", type: "select", options: ["Critical", "High", "Medium", "Low"], cypherField: "v.priority" },
    { id: "severity", label: "Severity", type: "select", options: ["Critical", "Severe", "Moderate", "Mild"], cypherField: "d.severity" },
    { id: "claimStatus", label: "Claim Status", type: "select", options: ["Approved", "Denied", "Pending", "Partial"], cypherField: "ic.status" },
    { id: "visitType", label: "Visit Type", type: "select", options: ["Emergency", "Outpatient", "Inpatient", "Follow-up", "Surgery"], cypherField: "v.type" },
    { id: "dateRange", label: "Date Range", type: "date", cypherField: "v.timestamp" },
  ],

  sampleQueries: [
    "readmissions within 30 days",
    "Dr. Sharma cardiac patients",
    "insurance denials for knee replacement",
    "diabetic patients on insulin",
    "protocol deviations in ICU",
    "ER wait time > 2 hours",
  ],

  constraints: [
    "CREATE CONSTRAINT profile_id IF NOT EXISTS FOR (p:Profile) REQUIRE p.profile_id IS UNIQUE",
    "CREATE CONSTRAINT identity_id IF NOT EXISTS FOR (i:Identity) REQUIRE i.identity_id IS UNIQUE",
    "CREATE CONSTRAINT visit_id IF NOT EXISTS FOR (v:Visit) REQUIRE v.visit_id IS UNIQUE",
    "CREATE CONSTRAINT diagnosis_id IF NOT EXISTS FOR (d:Diagnosis) REQUIRE d.diagnosis_id IS UNIQUE",
    "CREATE CONSTRAINT treatment_id IF NOT EXISTS FOR (t:Treatment) REQUIRE t.treatment_id IS UNIQUE",
    "CREATE CONSTRAINT medication_id IF NOT EXISTS FOR (m:Medication) REQUIRE m.medication_id IS UNIQUE",
    "CREATE CONSTRAINT provider_id IF NOT EXISTS FOR (pr:Provider) REQUIRE pr.provider_id IS UNIQUE",
    "CREATE CONSTRAINT claim_id IF NOT EXISTS FOR (ic:InsuranceClaim) REQUIRE ic.claim_id IS UNIQUE",
    "CREATE CONSTRAINT protocol_id IF NOT EXISTS FOR (pt:Protocol) REQUIRE pt.protocol_id IS UNIQUE",
    "CREATE CONSTRAINT outcome_id IF NOT EXISTS FOR (o:Outcome) REQUIRE o.outcome_id IS UNIQUE",
    "CREATE CONSTRAINT department_id IF NOT EXISTS FOR (dep:Department) REQUIRE dep.department_id IS UNIQUE",
    "CREATE CONSTRAINT commitment_id IF NOT EXISTS FOR (c:Commitment) REQUIRE c.commitment_id IS UNIQUE",
  ],

  indexes: [
    "CREATE INDEX profile_tenant IF NOT EXISTS FOR (p:Profile) ON (p._tenant)",
    "CREATE INDEX profile_name IF NOT EXISTS FOR (p:Profile) ON (p.name)",
    "CREATE INDEX identity_lookup IF NOT EXISTS FOR (i:Identity) ON (i.type, i.value, i._tenant)",
    "CREATE INDEX identity_value IF NOT EXISTS FOR (i:Identity) ON (i.value)",
    "CREATE INDEX visit_type IF NOT EXISTS FOR (v:Visit) ON (v.type)",
    "CREATE INDEX visit_department IF NOT EXISTS FOR (v:Visit) ON (v.department)",
    "CREATE INDEX visit_timestamp IF NOT EXISTS FOR (v:Visit) ON (v.timestamp)",
    "CREATE INDEX visit_priority IF NOT EXISTS FOR (v:Visit) ON (v.priority)",
    "CREATE INDEX diagnosis_severity IF NOT EXISTS FOR (d:Diagnosis) ON (d.severity)",
    "CREATE INDEX diagnosis_icd IF NOT EXISTS FOR (d:Diagnosis) ON (d.icd_code)",
    "CREATE INDEX claim_status IF NOT EXISTS FOR (ic:InsuranceClaim) ON (ic.status)",
    "CREATE INDEX provider_spec IF NOT EXISTS FOR (pr:Provider) ON (pr.specialization)",
    "CREATE INDEX protocol_status IF NOT EXISTS FOR (pt:Protocol) ON (pt.status)",
  ],
};
