name: Deploy
on:
  push:
    branches:
      - stage
    paths:
      - 'service-*/**'
  workflow_dispatch:
    inputs:
      service_path:
        description: "Service folder to deploy (e.g. service-one)."
        required: false
        type: string
jobs:
  deploy:
    uses: nurixlabs/hack-central-apr-26/.github/workflows/deploy.yml@main
    secrets: inherit
